project_id = "ulkxtkopehmiszfdjuys"

[functions.analyze-image]
verify_jwt = true

[functions.shopify-orders]
verify_jwt = false

[functions.integration-assistant]
verify_jwt = true

[functions.recover-failed-orders]
verify_jwt = true

[functions.import-shopify-orders]
verify_jwt = true

[functions.test-shopify-webhook]
verify_jwt = true

[functions.validate-shopify-connection]
verify_jwt = true

[functions.system-assistant]
verify_jwt = true

[functions.extract-invoice-total]
verify_jwt = true
